name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: установка питона
        uses: actions/setup-python@v2
        with:
          python-version: '3.13' 

      - name: установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit coverage

      - name: запуск тестов
        run: |
          coverage run -m unittest discover
          coverage report -m

      - name: линтинг кода
        run: |
          flake8 .

      - name: проверка безопасности
        run: |
          bandit -r .

      - name: уведомления в телеграм
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *${{ github.repository }}* CI/CD пайплайн завершен.
            *Статус*: ${{ job.status }}
